In [1]:
#sqs poll
import boto3
import json
import pandas as pd
import math
import os
import shutil
import numpy as np # linear algebra # data processing, CSV file I/O (e.g. pd.read_csv)
import cv2
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import keras
from keras.layers import Conv2D, MaxPool2D, Flatten, Dense, Dropout, BatchNormalization
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras import regularizers
from keras.models import model_from_json
import statistics 
from statistics import mode 

Using TensorFlow backend.


In [2]:
!python -m pip install tensorflow-gpu==1.11.0

     |████████████████████████████████| 258.8MB 49kB/s 
     |████████████████████████████████| 573kB 53.5MB/s 
     |████████████████████████████████| 3.0MB 42.4MB/s 
ERROR: xarray 0.15.1 has requirement setuptools>=41.2, but you'll have setuptools 39.1.0 which is incompatible.
ERROR: tensorflow 2.2.0rc4 has requirement tensorboard<2.3.0,>=2.2.0, but you'll have tensorboard 1.11.0 which is incompatible.
ERROR: google-auth 1.7.2 has requirement setuptools>=40.3.0, but you'll have setuptools 39.1.0 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
  Found existing installation: setuptools 46.1.3
    Uninstalling setuptools-46.1.3:
      Successfully uninstalled setuptools-46.1.3
  Found existing installation: tensorboard 2.2.1
    Uninstalling tensorboard-2.2.1:
      Successfully uninstalled tensorboard-2.2.1


In [3]:
cd /content/drive/My Drive/MC project/webinst/videos/tfjs-to-tf

/content/drive/My Drive/MC project/webinst/videos/tfjs-to-tf


In [4]:
pip install . --no-deps

Processing /content/drive/My Drive/MC project/webinst/videos/tfjs-to-tf
  Created wheel for tfjs-graph-converter: filename=tfjs_graph_converter-1.0.0-cp36-none-any.whl size=20277 sha256=7eec7dfef2aab4d18f4206e64a0cd420c40131e406154e87fe843602359838b4
  Stored in directory: /root/.cache/pip/wheels/11/d9/f4/4856730920807c20534a710d519e449079cf1c5c4710f64b9f
Successfully built tfjs-graph-converter


In [16]:
ls

'ASL alphabet video_team'/   finger_Spelling_model/   working/
'ASL alphabetvideo_team'/    webinst/


In [0]:
region_name = 'us-east-1'
queue_name = 'mcqueue'
max_queue_messages = 1
message_bodies = []
aws_access_key_id = 'AKIAJ7HUDAMTZBQ7L74A'
aws_secret_access_key = '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'
sqs = boto3.resource('sqs', region_name=region_name,aws_access_key_id=aws_access_key_id,aws_secret_access_key=aws_secret_access_key)
queue = sqs.get_queue_by_name(QueueName=queue_name)
while True:
  messages_to_delete = []
  for message in queue.receive_messages(MaxNumberOfMessages=max_queue_messages):
      # process message body
      body = json.loads(message.body)
      message_bodies.append(body)
      # add message to delete
      messages_to_delete.append({
          'Id': message.message_id,
          'ReceiptHandle': message.receipt_handle
      })
      filetodown = body["Records"][0]["s3"]["object"]["key"]
      #download the video
      #frameextractors
      print(filetodown)
      s3_client = boto3.client('s3',
                         aws_access_key_id=aws_access_key_id,
                         aws_secret_access_key= aws_secret_access_key)
      response = s3_client.list_objects(Bucket="mcrequests", Prefix="")
      for file in response['Contents']:
        name = file['Key'].rsplit('/', 1)
        print(name)
        if name[0] == filetodown:
          print("once")
          s3_client.download_file(Bucket="mcrequests", Key=file['Key'], Filename='/content/drive/My Drive/MC project/working/videos/frames/sav.mp4')
          #call frame extractor
          frameextract()
          posenet()
          segmentation()
          testdir = cropimages()
          result = cnnmodel(testdir)
          print(result)
          getresult(result)
          

  print(messages_to_delete)
  # if you don't receive any notifications the
      # messages_to_delete list will be empty
  if len(messages_to_delete) == 0:
      break
  # delete messages to remove them from SQS queue
  # handle any errors
  else:
      delete_response = queue.delete_messages(Entries=messages_to_delete)

In [17]:
frameextract()
posenet()
segmentation()
testdir = cropimages()
result = cnnmodel(testdir)
print(result)
getresult(result)

frame extraction started
/content/drive/My Drive/MC project/ASL alphabet video_team/Madhu/frames/A
frame extraction done
Posenet started
Posenet Completed
[23.0, 24.0, 29.0, 30.0]
cropping started
0
23.png
0
24.png
0
29.png
0
30.png
cropping done
cnn model started
cnn model done
[4 0 0 0]
The results are
[4 0 0 0]
The highest occuring
0
pushing into s3
s3 done


In [0]:
#frame extractor
def frameextract():
  print("frame extraction started")
  path_to_video_files = "/content/drive/My Drive/MC project/ASL alphabet video_team/Madhu"
  path_to_frames = path_to_video_files + '/frames/'
  path_to_video_files = path_to_video_files + '/'
  video_files = os.listdir(path_to_video_files)
  os.mkdir(path_to_frames)
  for file in video_files:
      video = cv2.VideoCapture(path_to_video_files + file)
      flip = False
      count = 0
      success = 1
      arr_img = []
      # If such a directory doesn't exist, creates one and stores its Images
      if not os.path.isdir(path_to_frames + os.path.splitext(file)[0] + "/"):
          os.mkdir(path_to_frames + os.path.splitext(file)[0])
          new_path = path_to_frames + os.path.splitext(file)[0]
          print(new_path)
          while success:
              success, image = video.read()
              # Frames when generated are getting rotated clockwise by above method, so correcting it
              #print(success)
              if success:
                  if flip:
                      print("flip")
                      image = cv2.rotate(image, cv2.ROTATE_90_CLOCKWISE)
                  arr_img.append(image)
                  #print(count)
                  count += 1
          # Sub sampling the number of frames
          # numbers = sorted(random.sample(range(len(arr_img)), 45))
          #print(len(arr_img))
          #cv2.imshow('x',arr_img[-1])
          #cv2.waitKey()
          count = 0
          for i in range(len(arr_img)):
              cv2.imwrite(new_path + "/%d.png" % count, arr_img[i])
              count += 1
  print("frame extraction done")

In [0]:
#posenet
import os
def posenet():
  print("Posenet started")
  os.system("!python /content/drive/My\ Drive/MC\ project/webinst/videos/posenet-pytorch-master/image_demo.py --model 101 --image_dir /content/drive/My\ Drive/MC\ project/ASL\ alphabet\ video_team/Madhu/frames/A")
  shutil.copyfile('/content/drive/My Drive/MC project/working/key_points.csv', '/content/drive/My Drive/MC project/ASL alphabet video_team/Madhu/frames/A/key_points.csv')
  print("Posenet Completed")
#posenet()

In [0]:
#convert to csv
def convert_to_csv():
    path_to_video = "/content/drive/My Drive/MC project/working/videos/frames/key_points"
    columns = ['score_overall', 'nose_score', 'nose_x', 'nose_y', 'leftEye_score', 'leftEye_x', 'leftEye_y',
               'rightEye_score', 'rightEye_x', 'rightEye_y', 'leftEar_score', 'leftEar_x', 'leftEar_y',
               'rightEar_score', 'rightEar_x', 'rightEar_y', 'leftShoulder_score', 'leftShoulder_x', 'leftShoulder_y',
               'rightShoulder_score', 'rightShoulder_x', 'rightShoulder_y', 'leftElbow_score', 'leftElbow_x',
               'leftElbow_y', 'rightElbow_score', 'rightElbow_x', 'rightElbow_y', 'leftWrist_score', 'leftWrist_x',
               'leftWrist_y', 'rightWrist_score', 'rightWrist_x', 'rightWrist_y', 'leftHip_score', 'leftHip_x',
               'leftHip_y', 'rightHip_score', 'rightHip_x', 'rightHip_y', 'leftKnee_score', 'leftKnee_x', 'leftKnee_y',
               'rightKnee_score', 'rightKnee_x', 'rightKnee_y', 'leftAnkle_score', 'leftAnkle_x', 'leftAnkle_y',
               'rightAnkle_score', 'rightAnkle_x', 'rightAnkle_y']
    data = json.loads(open(path_to_video + '.json', 'r').read())
    csv_data = np.zeros((len(data), len(columns)))
    for i in range(csv_data.shape[0]):
        one = []
        one.append(data[i]['score'])
        for obj in data[i]['keypoints']:
            one.append(obj['score'])
            one.append(obj['position']['x'])
            one.append(obj['position']['y'])
        csv_data[i] = np.array(one)
    pd.DataFrame(csv_data, columns=columns).to_csv(path_to_video + '.csv', index_label='Frames#')


In [7]:
cd /content/drive/My Drive/MC project/ASL alphabet video_team/Madhu/frames/A/output

/content/drive/My Drive/MC project/ASL alphabet video_team/Madhu/frames/A/output


In [0]:
#segmentation
def segmentation():
  df1 = pd.read_csv("/content/drive/My Drive/MC project/ASL alphabet video_team/Madhu/frames/A/key_points.csv")
  df1 = df1[["Frames#","rightWrist_y"]]
  x = 0
  init = 0
  flag = 0
  listofframes = []
  for index, row in df1.iterrows():
    if flag == 0:
      #get the decimal and integer part
      dec = math.modf(row['rightWrist_y'])
      #get the integer part
      init = (int(dec[1]))
      flag = 1
    else:
      #print(row['Frames#'], math.modf(row['rightWrist_y']))
      dec = math.modf(row['rightWrist_y'])
      #print(int(dec[1]))
      if x == int(dec[1]) and x < init - 100:
        #print(row['Frames#'], math.modf(row['rightWrist_y']))
        listofframes.append(row['Frames#'])
      x = int(dec[1])

  print(listofframes)

  ele = 1
  #flag_two = 0
  #flag_create = 0
  count_frames = 0
  filen = '/content/drive/My Drive/MC project/ASL alphabet video_team/Madhu/frames/A/output/'
  if (os.path.isdir(filen)) == False:
    os.mkdir(filen)
  while ele < len(listofframes):
    if(listofframes[ele] - listofframes[ele - 1] < 10):
      if (os.path.isdir(filen + str(count_frames)+'/')) == False:
        #create a directory and push it
        os.mkdir(filen + str(count_frames)+'/')
        shutil.copyfile('/content/drive/My Drive/MC project/ASL alphabet video_team/Madhu/frames/A/' + str(int(listofframes[ele - 1])) + '.png', '/content/drive/My Drive/MC project/ASL alphabet video_team/Madhu/frames/A/output/'+str(count_frames)+'/' + str(int(listofframes[ele - 1])) + '.png')
        #flag_two = 1
      else:
        shutil.copyfile('/content/drive/My Drive/MC project/ASL alphabet video_team/Madhu/frames/A/' + str(int(listofframes[ele - 1])) + '.png', '/content/drive/My Drive/MC project/ASL alphabet video_team/Madhu/frames/A/output/'+str(count_frames)+'/' + str(int(listofframes[ele - 1])) + '.png')
    else:
      shutil.copyfile('/content/drive/My Drive/MC project/ASL alphabet video_team/Madhu/frames/A/' + str(int(listofframes[ele - 1])) + '.png', '/content/drive/My Drive/MC project/ASL alphabet video_team/Madhu/frames/A/output/'+str(count_frames)+'/' + str(int(listofframes[ele - 1])) + '.png')
      #flag_two = 0
      count_frames = count_frames + 1
    ele = ele + 1
  shutil.copyfile('/content/drive/My Drive/MC project/ASL alphabet video_team/Madhu/frames/A/' + str(int(listofframes[ele - 1])) + '.png', '/content/drive/My Drive/MC project/ASL alphabet video_team/Madhu/frames/A/output/'+str(count_frames)+'/' + str(int(listofframes[ele - 1])) + '.png')

In [19]:
segmentation()

[23.0, 24.0, 29.0, 30.0]


In [0]:
#crop
import cv2
def cropimages():
  print("cropping started")
  for folder in os.listdir('/content/drive/My Drive/MC project/ASL alphabet video_team/Madhu/frames/A/output'):
    for image in os.listdir('/content/drive/My Drive/MC project/ASL alphabet video_team/Madhu/frames/A/output/'+folder):
      print(folder)
      df1 = pd.read_csv("/content/drive/My Drive/MC project/ASL alphabet video_team/Madhu/frames/A/key_points.csv")
      df1 = df1[["Frames#","rightWrist_y"]]
      for index, row in df1.iterrows():
        if(str(index) == str(image.split('.')[0])):
          print(image)
      #print(id(0) == id(image.split('.')[0]))
      image = '/content/drive/My Drive/MC project/ASL alphabet video_team/Madhu/frames/A/output/'+folder +'/'+image
      img = cv2.imread(image)
      #print(img)
      crop_img = img[631-300:631+50, 425-50:425+250]
      cv2.imwrite(image, crop_img)  
      #cv2.imshow("cropped", crop_img)
      cv2.waitKey(0)
  print("cropping done")
  return '/content/drive/My Drive/MC project/ASL alphabetvideo_team/Madhu/frames/A/output/'+folder

In [21]:
cropimages()

cropping started
0
23.png
0
24.png
0
29.png
0
30.png
cropping done


'/content/drive/My Drive/MC project/ASL alphabetvideo_team/Madhu/frames/A/output/0'

In [0]:
#cnn
def cnnmodel(test_dir):
  test_dir = '/content/drive/My Drive/MC project/ASL alphabetvideo_team/Madhu/frames/A/output/0'
  print("cnn model started")
  result = []
  images=[]
  size = 64,64
  #count = 0
  # for folder in os.listdir(test_dir):
  #     #images=[]
  for image in os.listdir(test_dir):
      temp_img = cv2.imread(test_dir + '/' + image)
      temp_img = cv2.resize(temp_img, size)
      images.append(temp_img)
      #print(type(images))
      #print(images)
      #print(len(images))
      #count = count + 1
      #print(count)
  images = np.array(images)
  images = images.astype('float32')/255.0
  json_file = open('/content/drive/My Drive/MC project/working/videos/keypoints/model.json', 'r')
  loaded_model_json = json_file.read()
  json_file.close()
  loaded_model = model_from_json(loaded_model_json)
  # load weights into new model
  loaded_model.load_weights("/content/drive/My Drive/MC project/working/videos/keypoints/model.h5")
  loaded_model.compile(optimizer = 'adam', loss = keras.losses.categorical_crossentropy, metrics = ["accuracy"])
  #print(loaded_model.summary())
  v = loaded_model.predict_classes(images)
  print("cnn model done")
  return v
      #images = []
  #new_model = model.load_weights('cnn.h5')
  #predictions = new_model.predict_classes(images)
  #print(predictions)


In [25]:
getoutput = cnnmodel("x")
getresult(getoutput)

cnn model started
cnn model done
The results are
[4 0 0 0]
The highest occuring
0
pushing into s3
s3 done


In [0]:
#getting result 
def getresult(result):
  print("The results are")
  print(result)
  sendoutput = []
  #print(getresult_i)
  freq = mode(result)
  print("The highest occuring")
  print(freq)
  sendoutput.append(freq)
  #pushing into s3
  print("pushing into s3")
  aws_access_key_id = 'AKIAJ7HUDAMTZBQ7L74A'
  aws_secret_access_key = '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'
  with open("/content/drive/My Drive/MC project/working/videos/text/file.txt", "w") as output:
      output.write(str(sendoutput))
  s3_client = boto3.client('s3',aws_access_key_id=aws_access_key_id,aws_secret_access_key= aws_secret_access_key)
  s3_client.upload_file('/content/drive/My Drive/MC project/working/videos/text/file.txt', 'mcoutputreq', 'testfordemo.txt')
  print("s3 done")

In [0]:
pwd

'/content'